PROCESS BEFORE OUTPUT.
 MODULE STATUS_9002.

*     LOOP AT  LT_TRACK
*        INTO LS_TRACK
*       WITH CONTROL PWTRACK
*       CURSOR PWTRACK-CURRENT_LINE.
**    MODULE ZHAZARD_GET_LINES.
*  ENDLOOP.

*
PROCESS AFTER INPUT.

* LOOP AT LT_TRACK.
* module PW_read_table_control.
*
*  ENDLOOP.
 MODULE USER_COMMAND_9002.
